# Generated by Django 4.2.5 on 2023-11-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
