# Generated by Django 4.2.5 on 2023-11-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
